version: '3.9'
services:
  superset:
    build: .
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    ports:
      - "8088:8088"
    environment:
      REDIS_URL: "redis://redis:6379/0"
    volumes:
      - superset_home:/app/superset_home
      - ./superset_config.py:/app/superset_config.py

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: superset
      MYSQL_USER: data
      MYSQL_PASSWORD: sh2vfaKW89uH
      MYSQL_ROOT_PASSWORD: sh2vfaKW89uH
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  superset_home:
  mysql_data:
  redis_data:
